# Generated by Django 4.2.8 on 2024-11-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("cms", "0009_rename_discharge_date")]

    operations = [
        migrations.AlterField(
            model_name="ward",
            name="nickname",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nickname of this ward",
                max_length=32,
                verbose_name="ward nickname",
            ),
        )
    ]
