# Generated by Django 4.2.8 on 2024-11-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("cms", "0010_alter_ward_nickname")]

    operations = [
        migrations.AlterField(
            model_name="ward",
            name="nickname",
            field=models.CharField(
                blank=True,
                help_text="Nickname of this ward",
                max_length=32,
                verbose_name="ward nickname",
            ),
        )
    ]
