# Generated by Django 4.2.8 on 2024-12-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("cms", "0013_merge_20241205_1258")]

    operations = [
        migrations.AlterField(
            model_name="floor",
            name="code",
            field=models.CharField(
                help_text="Nickname of the floor",
                max_length=10,
                unique=True,
                verbose_name="floor code",
            ),
        )
    ]
