[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
name = "ycms"
description = "..."
authors = [
    { name = "...", email = "x@x.x" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 4.2",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "django>=4.2,<5.0",
    "django-debug-toolbar",
    "django-webpack-loader",
    "django-widget-tweaks",
    "django-mathfilters",
    "pillow",
    "psycopg[binary]",
    "python-magic",
    "pandas",
]
keywords = ["..."]
license = { text = "Apache2 2.0 License" }
requires-python = ">=3.9"
dynamic = ["version"]


[project.optional-dependencies]
dev = [
    "black",
    "build",
    "bumpver",
    "djlint",
    "isort",
    "looseversion",
    "pre-commit",
    "pyjwt",
    "pylint",
    "pylint-django",
    "pylint-per-file-ignores",
    "pytest-circleci-parallelized",
    "pytest-cov",
    "pytest-django",
    "pytest-testmon",
    "pytest-xdist",
    "pytest-icdiff",
    "sphinx",
    "sphinxcontrib-django",
    "sphinx-last-updated-by-git",
    "sphinx-rtd-theme",
    "twine",
]
pinned = [
    "asgiref==3.7.2",
    "Django==4.2.8",
    "django-debug-toolbar==4.2.0",
    "django-webpack-loader==3.0.0",
    "django-widget-tweaks==1.5.0",
    "Pillow==10.1.0",
    "psycopg==3.1.16",
    "psycopg-binary==3.1.16",
    "python-magic==0.4.27",
    "sqlparse==0.4.4",
    "typing_extensions==4.9.0",
]
dev-pinned = [
    "alabaster==0.7.13",
    "astroid==3.0.2",
    "Babel==2.14.0",
    "black==23.12.1",
    "build==1.0.3",
    "bumpver==2023.1129",
    "certifi==2023.11.17",
    "cffi==1.16.0",
    "cfgv==3.4.0",
    "charset-normalizer==3.3.2",
    "click==8.1.7",
    "colorama==0.4.6",
    "coverage==7.3.4",
    "cryptography==41.0.7",
    "cssbeautifier==1.14.11",
    "dill==0.3.7",
    "distlib==0.3.8",
    "djlint==1.34.1",
    "docutils==0.20.1",
    "EditorConfig==0.12.3",
    "exceptiongroup==1.2.0",
    "execnet==2.0.2",
    "filelock==3.13.1",
    "html-tag-names==0.1.2",
    "html-void-elements==0.1.0",
    "icdiff==2.0.7",
    "identify==2.5.33",
    "idna==3.6",
    "imagesize==1.4.1",
    "importlib-metadata==7.0.1",
    "iniconfig==2.0.0",
    "isort==5.13.2",
    "jaraco.classes==3.3.0",
    "jeepney==0.8.0",
    "Jinja2==3.1.2",
    "jsbeautifier==1.14.11",
    "json5==0.9.14",
    "keyring==24.3.0",
    "lexid==2021.1006",
    "looseversion==1.3.0",
    "markdown-it-py==3.0.0",
    "MarkupSafe==2.1.3",
    "mccabe==0.7.0",
    "mdurl==0.1.2",
    "more-itertools==10.1.0",
    "mypy-extensions==1.0.0",
    "nh3==0.2.15",
    "nodeenv==1.8.0",
    "packaging==23.2",
    "pathspec==0.12.1",
    "pkginfo==1.9.6",
    "platformdirs==4.1.0",
    "pluggy==1.3.0",
    "pprintpp==0.4.0",
    "pre-commit==3.6.0",
    "pycparser==2.21",
    "Pygments==2.17.2",
    "PyJWT==2.8.0",
    "pylint==3.0.3",
    "pylint-django==2.5.5",
    "pylint-per-file-ignores==1.3.2",
    "pylint-plugin-utils==0.8.2",
    "pyproject_hooks==1.0.0",
    "pytest==7.4.3",
    "pytest-circleci-parallelized==0.1.0",
    "pytest-cov==4.1.0",
    "pytest-django==4.7.0",
    "pytest-icdiff==0.9",
    "pytest-testmon==2.1.0",
    "pytest-xdist==3.5.0",
    "PyYAML==6.0.1",
    "readme-renderer==42.0",
    "regex==2023.12.25",
    "requests==2.31.0",
    "requests-toolbelt==1.0.0",
    "rfc3986==2.0.0",
    "rich==13.7.0",
    "SecretStorage==3.3.3",
    "six==1.16.0",
    "snowballstemmer==2.2.0",
    "Sphinx==7.2.6",
    "sphinxcontrib-applehelp==1.0.7",
    "sphinxcontrib-devhelp==1.0.5",
    "sphinxcontrib-django==2.5",
    "sphinxcontrib-htmlhelp==2.0.4",
    "sphinxcontrib-jquery==4.1",
    "sphinxcontrib-jsmath==1.0.1",
    "sphinxcontrib-qthelp==1.0.6",
    "sphinxcontrib-serializinghtml==1.1.9",
    "sphinx-last-updated-by-git==0.3.6",
    "sphinx-rtd-theme==2.0.0",
    "toml==0.10.2",
    "tomli==2.0.1",
    "tomlkit==0.12.3",
    "tqdm==4.66.1",
    "twine==4.0.2",
    "urllib3==2.1.0",
    "virtualenv==20.25.0",
    "zipp==3.17.0",
]

[project.urls]
"Source Code" = "https://github.com/charludo/ycms"
"Issues" = "https://github.com/charludo/ycms/issues"

[tool.setuptools]
script-files = ["ycms/ycms-cli"]
license-files = ["LICENSE.txt", "NOTICE.md"]

[tool.setuptools.dynamic]
version = { attr = "ycms.__version__" }

[tool.setuptools.packages.find]
include = ["ycms*"]

[tool.bumpver]
current_version = "2023.10.0"
version_pattern = "YYYY.MM.INC0[-TAG]"
commit_message = """
Bump version to {new_version}

[skip ci]
"""


[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
]
"ycms/__init__.py" = [
    '__version__ = "{version}"',
]
"docs/src/conf.py" = [
    'release = "{version}"',
]

[tool.black]
skip-magic-trailing-comma = true

[tool.djlint]
profile="django"

[tool.isort]
profile = "black"
order_by_type = false

[tool.pylint.main]
jobs = 0
load-plugins = [
    "pylint_django",
    "pylint_per_file_ignores",
    "pylint.extensions.code_style",
    "pylint.extensions.comparison_placement",
    "pylint.extensions.consider_ternary_expression",
    "pylint.extensions.docparams",
    "pylint.extensions.for_any_all",
]
enable = [
    "consider-using-augmented-assign",
]
disable = [
    "consider-using-namedtuple-or-dataclass",
    "consider-using-tuple",
    "duplicate-code",
]
recursive = true
ignore-paths = [
  ".venv",
  "node_modules",
  "build",
]
fail-on = "I"
django-settings-module="ycms.core.settings"

[tool.pylint.design]
max-args = 7
max-attributes = 7
max-branches = 12
max-locals = 15
max-parents = 7

[tool.pylint.messages_control]
disable = [
    "invalid-name",
    "line-too-long",
    "too-many-lines",
    "missing-module-docstring",
    "no-member",
    "unsupported-binary-operation",
    "deprecated-module",
]
enable = [
    "useless-suppression",
]

[tool.pylint.reports]
output-format = "colorized"

[tool.pylint-per-file-ignores]
"/tests/"="unused-argument,missing-function-docstring"

[tool.coverage.run]
omit = ["ycms/core/management/commands/*", "ycms/core/circleci_settings.py", "ycms/core/wsgi.py"]
