# Generated by Django 4.2.8 on 2024-11-24 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add a mask field for specifying on which days of the week a ward allows discharges
    """

    dependencies = [("cms", "0009_rename_discharge_date")]

    operations = [
        migrations.AddField(
            model_name="ward",
            name="allowed_discharge_days",
            field=models.SmallIntegerField(
                default=127,
                help_text="Days of the week where discharges are allowed in this ward",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(127),
                ],
                verbose_name="allowed discharge days",
            ),
        )
    ]
