# Generated by Django 4.2.8 on 2024-12-02 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0010_add_ward_allowed_discharge_days"),
        ("cms", "0010_remove_ward_ward_number_ward_nickname"),
    ]

    operations = []
