# Generated by Django 4.2.8 on 2024-12-05 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0011_merge_20241202_1759"),
        ("cms", "0012_alter_floor_code_alter_floor_name"),
    ]

    operations = []
