# Generated by Django 4.2.8 on 2025-01-11 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Add medical specialization field to medical records that specify the treatment specialization (Fachrichtung).
    """

    dependencies = [("cms", "0014_alter_floor_code_alter_ward_floor")]

    operations = [
        migrations.CreateModel(
            name="MedicalSpecialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of this medical specialization.",
                        max_length=256,
                        verbose_name="specialization name",
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        help_text="Abbreviation of this medical specialization.",
                        max_length=8,
                        verbose_name="abbreviation",
                    ),
                ),
            ],
            options={
                "verbose_name": "medical specialization",
                "verbose_name_plural": "medical specializations",
            },
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="medical_specialization",
            field=models.ForeignKey(
                blank=True,
                help_text="Medical specialization of the patient's treatment.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cms.medicalspecialization",
                verbose_name="medical specialization",
            ),
        ),
    ]
