# Generated by Django 4.2.8 on 2025-01-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("cms", "0015_add_medical_specialization")]

    operations = [
        migrations.AlterField(
            model_name="icd10entry",
            name="code",
            field=models.CharField(
                help_text="ICD-10-GM classification code",
                max_length=21,
                unique=True,
                verbose_name="code",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="room", unique_together={("room_number", "ward")}
        ),
        migrations.AlterUniqueTogether(
            name="ward", unique_together={("floor", "name")}
        ),
    ]
