# Generated by Django 4.2.8 on 2025-01-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0016_alter_icd10entry_code_alter_room_unique_together_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="bed",
            name="bed_blocking_reason",
            field=models.CharField(
                blank=True,
                help_text="Reason why the bed is blocked",
                max_length=256,
                null=True,
                verbose_name="bed blocking reason",
            ),
        ),
        migrations.AddField(
            model_name="bed",
            name="bed_blocking_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOTBLOCKED", "-------"),
                    ("DOCTORSHORTAGE", "Shortage of doctors"),
                    ("DOCTORCAREGIVERSHORTAGE", "Shortage of doctors and caregivers"),
                    ("NOTOPERATED", "Currently not in operation"),
                    ("INFECTIOUS", "Infectious"),
                    ("CONSTRUCTION", "Construction/repair"),
                    ("RESERVED", "Reserved for patient"),
                    ("MEDREASON", "Med. reason/incompliance"),
                    ("PALLIATIVE", "Palliative"),
                    ("CAREGIVERSHORTAGE", "Shortage of caregivers"),
                    ("OS", "Optional service"),
                    ("OSSRL", "OS SR large"),
                    ("OSSRS", "OS SR small"),
                    ("OSRR", "OS room rate"),
                    ("FRANZISKUS", "Franziskus"),
                ],
                help_text="The bed might be blocked",
                max_length=23,
                null=True,
                verbose_name="bed blocking type",
            ),
        ),
    ]
